/* SecondLook — a small everyday dictionary used to spot misspellings in messages.
 * It doesn't need to be complete: every score is compared with how YOU usually text,
 * and the misspelling rate is compared with your own usual rate, so names and slang the list lacks are already "normal" for you. */
(function (root) {
  'use strict';
  var WORDS = [
    // everyday English
    'a about above across act actually add after afternoon again against age ago agree ah ahead air all almost alone along',
    'already alright also always am amazing an and angry another answer any anybody anyone anything anyway anywhere apartment',
    'app are area arent arm around arrive arrived as ask asked at ate aunt away awesome awful baby back bad bag bank bar bars',
    'be beach beautiful because bed been beer beers before behind being believe below best better between big bike bill bit',
    'black blue body book boring born both bottle bought box boy brain bread break breakfast bring bro brother brought brown',
    'bus busy but buy by bye cab call called calling calm came can cannot cant car card care careful carry case cash cat catch',
    'cause chair chance change charge charger chat cheap check cheers chill city class clean clear close closed club coat coffee',
    'cold college come comes coming cool corner could couldnt couple course cousin crazy cry cup cut dad damn dance dark date',
    'day days dead deal dear did didnt die different dinner do doctor does doesnt dog doing done dont door double down drink',
    'drinking drinks drive driven driver driving drop dropped drove drunk during each early easy eat eating eight either else',
    'empty end enjoy enough even evening event ever every everybody everyone everything exactly except excited excuse eye eyes',
    'face fact fair fall family far fast feel feeling feet fell felt few fight final find fine finish finished fire first five',
    'floor food foot for forget forgot four free friday friend friends from front full fun funny game games gas gate gave get',
    'gets getting girl girls give given glad glass go god goes going gone gonna good got great green group guess guy guys had',
    'hair half hand hands happen happened happy hard has hasnt hate have havent having he head heading hear heard heart hello',
    'help her here hers hes hey hi high him himself his hit hold home honest honestly hope hot hour hours house how however',
    'huge hungry hurry hurt husband i ice id idea if ill im important in inside instead into is isnt it its itself ive job join',
    'joke just keep keys key kid kids kind kinda kitchen knew know known last late later laugh leave leaving left leg less let',
    'lets life light like line list listen little live lives lol long look looked looking looks lost lot lots loud love low luck',
    'lunch mad made main make makes making man many market matter may maybe me mean means meet meeting met middle might mind',
    'mine minute minutes miss missed mom money month more morning most mother move movie much music must my myself name near',
    'need needs never new news next nice night nine no nobody noise none nor not nothing now number of off office ok okay old',
    'on once one ones only open or order other others our out outside over own pack paid parents park parking part party pass',
    'past pay people person phone pick picked picture place plan play please point police poor pretty probably problem pull',
    'put question quick quickly quiet quite rain rather reach read ready real really reason red remember rest ride right river',
    'road room run safe safely said same saturday saw say says school second see seem seems seen send sent seriously set seven',
    'she shes shit short should shouldnt show shut sick side since single sister sit six sleep slow slowly small smell so some',
    'somebody someone something sometimes somewhere son soon sorry sound speak spend stand start started station stay still',
    'stop store story straight street stuck stuff such sunday super sure take taken taking talk tell ten than thank thanks that',
    'thats the their them then there theres these they theyre thing things think this those though thought three through till',
    'time tired to today together told tomorrow tonight too took top totally town traffic train tried trip true trust try',
    'trying turn two under understand until up upset us use used very wait waiting wake walk walking wall wanna want wanted',
    'wants warm was wasnt watch water way we wear weather week weekend weird well went were werent what whatever whats when',
    'where which while white who whole whose why wife will win window with without woke woman won wont word words work world',
    'worried worry would wouldnt write wrong yeah year years yes yesterday yet you youd youll young your youre yours yourself',
    'youve wed well weve theyll theyve shell hed hell',
    // more everyday English (work, email, study, home, feelings)
    'ability able absolutely accept access accident account achieve acting action active activity actual added adding address',
    'admit adult advance advice afraid afford agenda agent airport album alarm alive allow allowed amount analysis',
    'ancient angle animal announce annual answered anxious apart apologize apparently appear apple application apply appointment',
    'appreciate approach approval approve april argue argument army arrange arrangement arrival art article artist asleep',
    'assignment assist assistant assume attach attached attachment attack attempt attend attention attitude audience august',
    'author available average avoid awake award aware awkward background backup badly balance ball band base based basic',
    'basically basis bath bathroom battle bear beat became become becomes bedroom began begin beginning behave believed belong',
    'benefit beside besides bet beyond billion bird birth birthday bite blame blank blanket blind block blog blood blow board',
    'boat bone bonus boot border borrow boss bother bottom bowl brand brave breath breathe brief bright brilliant broke broken',
    'budget bug build building built bunch burn button cake calendar camera camp campus cancel cancelled candidate cap capital',
    'captain career carefully category ceiling celebrate cell center central century certain certainly chain challenge',
    'champion channel chapter character charged chart chase cheaper cheese chef chest chicken chief child children choice',
    'choose chose chosen church cinema circle citizen claim classes classic client climb clock clothes cloud coach code',
    'colleague collect collection colour color column combine comfortable comment commercial commit committee common communicate',
    'community company compare comparison competition complain complaint complete completely complex complicated computer concept',
    'concern concerned concert conclusion condition conference confidence confident confirm confirmed confused connect connection',
    'consider considering constant contact contain content contest context continue contract control conversation convince cook',
    'cookie cooking copy correct cost costs cottage cotton couch count counter country countries county courage court cover',
    'covered crash cream create created creative credit crew crime crisis critical cross crowd crowded culture curious current',
    'currently customer cute cycle daily damage dangerous data database daughter deadline dealing death debate debt decade',
    'december decide decided decision deep deeply defend define definitely degree delay delete deliver delivery demand dentist',
    'department depend deposit describe description design desk despite detail details determine develop development device',
    'diet difference difficult digital direct direction directly director dirty disagree disappear discount discover discuss',
    'discussion disease dish distance district divide document documents dollar dollars domain dozen draft drag drama draw drawing',
    'dream dress dressed drew drug dry due dumb duty earlier earn earth ease easily east eaten economy edge edit editor education',
    'effect effective effort egg elect election electric element email emails emergency emotion emotional employee employer',
    'energy engine engineer enormous ensure enter entire entirely entrance entry environment episode equal equipment error escape',
    'especially essay estimate etc evaluate everywhere evidence evil exact exam example excellent exchange exciting exercise exist',
    'exit expect expected expensive experience experiment expert explain explanation express extra extremely fabulous',
    'factor factory fail failed failure faith fake familiar famous fan fancy fantastic fashion fat father fault favor favorite',
    'favourite fear feature february fee feedback female fever field fifty figure file files fill film finally finance financial',
    'finger firm fish fit fix fixed flight flower fly focus folder folks follow following fool football force forever form',
    'formal former forward found foundation frame freedom french fresh fridge fruit fuel fully function fund funds future gain',
    'gallery gap garden gather gear general generally generation gentle genuine gift girlfriend boyfriend goal gold golf goodbye',
    'grab grade graduate grand grandma grandpa grant grass grateful greatest grew grocery ground grow growing',
    'growth guard guest guide guilty guitar gym habit hall handle hang hanging happening happiness harm hat health',
    'healthy heat heavy height helpful helping hero hidden hide highly hill hire history hobby hole holiday homework honey',
    'hopefully horrible horse hospital host huh human humor hundreds hunt hurts ideal ideas identify identity ignore',
    'ill illegal image imagine immediately impact importance impossible impress improve improvement inch include included including',
    'income increase incredible indeed independent india indian individual industry info inform information injury inner input',
    'insane insurance intended interest interested interesting internal international internet interview introduce invest',
    'investment invitation invite invited involve involved issue issues item items jacket january jeans',
    'jewelry joined journey joy judge july jump june junior justice keen kept kick kiss knee knife knock',
    'knowledge lab label lack lady lake land language laptop large largest latest law lawyer lay layer lazy lead leader',
    'league learn learned learning least leather lecture legal lesson letter level library lie likely limit link links',
    'lip liquid listening literally loan local located lock logic login lonely loose lord lose losing loss lovely lower lucky',
    'machine magazine magic mail major majority male mall manage management manager march mark marriage married mask mass massive',
    'master match material math maths meal meaning meanwhile measure meat media medical medicine medium member members memory',
    'mental mention menu mess messages metal method mile military milk million minor mirror mission mistake mix mobile',
    'model modern moment monthly mood moon moral motor mountain mouth movies moving mum muscle museum mystery nation',
    'national natural nature nearly neat necessary neck negative neighbor neighbour nervous network newspaper nod normal',
    'normally north nose note notes notice november nurse object obvious obviously occasion ocean october offer officer official',
    'often oil online onto operation opinion opportunity option orange ordered organization original otherwise ought ours',
    'ourselves outcome overall owe owner package page pages pain paint pair pan panel paper paragraph parent partner parts passed',
    'passenger password pasta patient pattern payment peace pen pencil percent perfect perfectly perform performance perhaps',
    'period permission personal personally pet phase photo photos phrase physical piano piece pink plane planet planning',
    'plans plant plastic plate platform player players pleasant pleased pleasure plenty plus pocket poem poet policy polite',
    'political politics pool pop popular population position positive possible possibly post potato pound power powerful',
    'practice pray prefer pregnant prepare prepared presentation president press pressure price pride primary prince princess',
    'print prior priority prison private prize pro process produce product production professional professor profile profit',
    'program programme progress project projects promise promote proof proper properly property propose protect proud prove',
    'provide public publish purple purpose push quality quarter queen queue quit race radio raise ran random range rank rare',
    'rate rating raw react reaction reader reading reality realize realized realise receive received recent recently recipe',
    'recognize recommend record recover reduce refer reference reflect refund refuse regarding region regular regularly reject',
    'relationship relax release relevant relief religion rely remain remind reminder remote remove rent repair repeat replace',
    'replied reply report reports represent request require required research resource respect respond response responsible',
    'result results resume return returned reveal review reviews reward rich rid ring rise risk rock role roll',
    'romantic roof root rose rough round route routine row royal rude rule rules rush sad safety salad salary sale salt sample',
    'sand sandwich save saved saving scale scared scary scene schedule science score screen script sea search season seat',
    'secret section secure security select self sell semester senior sense sensitive sentence separate september series serious',
    'serve server service session setting settle seventy several severe shade shake shall shame shape share shared sharp',
    'sheet shelf shift shine ship shirt shock shoe shoes shoot shop shopping shoulder shout shower shy sibling sight sign signal',
    'signed silence silent silly silver similar simple simply sing singer sink sir site situation size skill skills skin skip',
    'sky slack slept slide slightly slip smart smile smoke smooth snow soap social society sock sofa soft software soldier',
    'solid solution solve somehow song sort soul source south space spare speaker special specific speech speed spell',
    'spending spent spicy spirit split spoke sport sports spot spread spring square staff stage stairs stamp standard star stare',
    'stars state statement stats status steal step stick sticker stock stomach stone stood stopped storm strange stranger',
    'strategy stream strength stress stressed stretch strict strike string strong structure student students studio study',
    'stupid style subject submit success successful suck sudden suddenly suffer sugar suggest suggestion suit suitcase summary',
    'summer sun sunny supply support suppose supposed surface surgery surprise surprised survey survive suspect sweet swim',
    'switch symbol system table tablet tail talent talked talking tall target task tasks taste tax tea teach teacher team teams',
    'tear tech technical technology teeth telephone television temperature temple tend tennis term terms terrible test tested',
    'tests text texted texting theme theory therapy therefore thick thin thinking third thirsty thousand threat throat throw',
    'thus ticket tickets tie tight tiny tip title toast toe toilet tone tongue tool tools tooth topic total touch tough tour',
    'tourist toward towards towel tower toy track trade tradition training transfer translate transport travel treat treatment',
    'tree trend trial trick trouble truck truly truth type typical ugly umbrella uncle unfortunately uniform union',
    'unique unit united university unless unlikely unusual update updated updates upon upstairs urgent useful user users usual',
    'usually vacation valley valuable value van variety various vegetable vehicle version via video videos view village visit',
    'visitor voice volume vote wage waited waiter walked wallet wander war warn warning wash waste watched watching wave weak',
    'wealth weapon website wedding weekly weight welcome west wet whenever wherever whether whilst whisper wide wild willing',
    'wind winner winter wire wise wish witness wonder wonderful wood wooden wool worker workers working workshop worse',
    'worst worth wow wrap writer writing written wrote yard yellow yoga zone',
    'dear regards sincerely kindly asap fyi cc',
    // numbers & time
    'zero eleven twelve fifteen twenty thirty hundred am pm tonight midnight monday tuesday wednesday thursday',
    // night out
    'pub bartender shots shot wine vodka whiskey rum tequila gin cocktail cocktails sober wasted tipsy buzzed hangover snacks',
    'pizza burger fries restaurant hotel hostel flat roommate bestie babe mate buddy dude bruh taxi uber ola rapido auto metro',
    'lyft pickup cab driver keys location address map maps battery dead charger lift',
    // texting
    'brb btw idk ikr imo lmao lmk np omg pls plz rn smh tbh thx ty ur wyd wya hbu ya yea yep yup nah nope kk hmm haha hahaha',
    'lmfao ttyl gn gm fr ngl af bday xoxo cya coz cuz tho yall gotta gotcha sorta dunno lemme gimme outta aint ok okk okay',
    // hinglish
    'haan han nahi nhi kya kyu kyun hai hain kar karo raha rahe rahi ho hoga bhai yaar acha accha achha theek thik chal chalo',
    'kaha kahan ghar main mai tum tu aap abhi bas kal aaj bhi na ki ka ke ko se pe mujhe mera meri tera teri kuch sab bahut',
    'bohot jaldi ruk ruko aaja aao jao pahuch pahunch gaya gayi gaye mat bol bolo sun suno pata nai',
    // names used in the demo
    'alex priya jordan sam mike'
  ].join(' ');

  if (typeof module === 'object' && module.exports) module.exports = WORDS;
  else root.SL_WORDS = WORDS;
})(typeof self !== 'undefined' ? self : this);
